      - name: Pull Latest Code from Private HF
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }} 
        run: |
          # Dhyan rahe, yahan sahi URL format daalna
          HF_REPO_URL="https://user:${HF_TOKEN}@huggingface.co/spaces/ksksysy540/pinteresto"
          
          git remote add hf "$HF_REPO_URL"
          
          # Sabse pehle remote se saari branches fetch karo
          git fetch hf
          
          # Ye check karega remote branches (Debugging ke liye)
          git branch -r
          
          # Forcefully HF ki main branch ko GitHub ki current branch me merge karo
          git pull hf main --rebase
