name: Pinteresto Cloud Runner

on:
  schedule:
    # US Prime Time ke hisaab se har 6 ghante mein (EST Focus)
    - cron: '0 */6 * * *'
  workflow_dispatch: # Manual test ke liye button

jobs:
  execute-bot:
    runs-on: ubuntu-latest # Yahan milega 7GB RAM aur 2 CPU
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install All Tools
        run: |
          pip install -r requirements.txt
          # Agar Playwright/Chromium use ho raha hai image process ke liye:
          # python -m playwright install chromium

      - name: Run Pinteresto Agent
        env:
          # Saare Secrets yahan link karo (GitHub Settings se uthayega)
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          CEREBRAS_API_KEY: ${{ secrets.CEREBRAS_API_KEY }}
          GOOGLE_CREDS_JSON: ${{ secrets.GOOGLE_CREDS_JSON }}
          SPREADSHEET_ID: ${{ secrets.SPREADSHEET_ID }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
         # TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
          MAKE_WEBHOOK_URL: ${{ secrets.MAKE_WEBHOOK_URL }}
          MAKE_WEBHOOK_URL_2: ${{ secrets.MAKE_WEBHOOK_URL_2 }}
        run: python run_now.py
