name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  # Isse tum manually bhi trigger kar sakte ho GitHub se
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Username ki jagah tumhara HF handle use kiya hai for better clarity
          git push --force https://ksksysy540:$HF_TOKEN@huggingface.co/spaces/ksksysy540/pinteresto main
